### ISSUE TITLE
Complex class documentation lists `#~` method. However the method is not actually available.

### ISSUE THREAD

**Issue by singhshivam** [rdoc/rdoc#349]
If you check the documentation for Complex class here:
http://ruby-doc.org/core-2.2.1/Complex.html

It lists #~ exists. However it does not actually.

Also the provided link http://ruby-doc.org/core-2.2.1/Complex.html#method-i-7E points nowhere useful.

**Comment by singhshivam** [comment]
If you check the documentation for Complex class here:
http://ruby-doc.org/core-2.2.1/Complex.html

It lists `#~` exists. However it does not actually.

Also the provided link http://ruby-doc.org/core-2.2.1/Complex.html#method-i-7E points nowhere useful.

**Comment by zzak** [comment]
It actually looks like it was defined at one time, but has since been disabled.. as you can see from ruby trunk:

```c
2204     rb_define_method(rb_cComplex, "conjugate", nucomp_conj, 0);
2205     rb_define_method(rb_cComplex, "conj", nucomp_conj, 0);
2206 #if 0
2207     rb_define_method(rb_cComplex, "~", nucomp_conj, 0); /* gcc */
2208 #endif
```

It was actually calling the same function `nucomp_con` which is just `#conjugate`.

I'm also guessing that RDoc doesn't care about `#if 0` and continues to parse these methods as if they are actually defined.

We could fix this on ruby trunk by patching `complex.c` to use `:nodoc:` for these methods instead.

Giving this a close since there's nothing we can do in RDoc itself here. Thanks for your report!
